version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./certs:/certs
    command: [ "gunicorn", "-b", "0.0.0.0:5000","app:app"]
    networks:     
      - my_network

  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" # avoid conflicts
    volumes:
      - ./my_flask_app.conf:/etc/nginx/conf.d/my_flask_app.conf
      - ./certs:/certs
      - ./static:/usr/share/nginx/html/static
    environment:
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
    depends_on:
      - web
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
